  version: '3.3'
  services:
    app:
      container_name: per-diem-task
      restart: always
      build: .
      ports:
        - 5300:5300
      links:
        - mongo
        - redis
    mongo:
      container_name: mongo
      image: mongo
    redis:
      container_name: redis
      image: "redis:alpine"
      command: redis-server /Users/mac/etc/redis/redis.conf --requirepass mypassword
      ports: 
        - 6379:6379
      volumes: 
        - $PWD/redis.conf:/Users/mac/etc/redis/redis.conf