  version: '3.3'
  services:
    app:
      container_name: per-diem-task
      restart: always
      build: .
      ports:
        - 5300:5300
      links:
        - mongo
    mongo:
      container_name: mongo
      image: mongo
    redis:
      image: redis:latest
      command: ["redis-server", "--bind", "redis", "--port", "6379"]